### ISSUE TITLE
Installing the database Odoo via ansible

### ISSUE THREAD

**Issue by collex100** [infOpen/ansible-role-odoo#52]
Can I use the ansible to give such commands:

`$ ./odoo-bin shell`
```
$ from openerp.service import db
db.exp_create_database('dbname',False,'ru_RU','admin','admin')
```
or
`$ ./odoo-bin -d dbname -i crm,sale --without-demo=all`

If yes, then please help how it can be done.

Thanks!

**Comment by achaussier** [comment]
Hello,

Sorry, I've not see your issue when you wrote it.
I archive this repository so I close your issue.

Have a nice day
